language: node_js
matrix:
  fast_finish: true
node_js:
  - '8'
  - '7'
  - '6'
  - '5'
  - '4'
env:
  - NPM_VERSION=4.1.1
  - NPM_VERSION=4.1.0
  - NPM_VERSION=4.0.5
  - NPM_VERSION=4.0.3
  - NPM_VERSION=4.0.2
  - NPM_VERSION=4.0.1
  - NPM_VERSION=4.0.0
  - NPM_VERSION=3.10.10
  - NPM_VERSION=3.10.9
  - NPM_VERSION=3.10.8
  - NPM_VERSION=3.10.7
  - NPM_VERSION=3.10.6
  - NPM_VERSION=3.10.5
script:
  - NPM_VERSION=$NPM_VERSION npm test
